# Book settings
title: 
author: David Whipp and Lars Kaislaniemi
copyright: '2020'
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  thebelab                  : true
